name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Test FTP connectivity
        run: |
          echo "Testing FTP server connectivity..."
          ping -c 3 ${{ secrets.FTP_HOST }} || echo "Ping failed, but FTP might still work"
          nslookup ${{ secrets.FTP_HOST }} || echo "DNS lookup failed"

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: dist/
          server-dir: /
          dangerous-clean-slate: true
          timeout: 60000